import mongoose from 'mongoose'
import Product from './models/Product.js'

const products = [
  {
    title: 'Apple iPhone 16 Pro',
    brand: 'Apple',
    category: 'Mobiles',
    price: 1299,
    oldPrice: 1499,
    discountPercentage: 13,
    description: 'This flagship smartphone delivers a premium experience with a stunning OLED display, advanced camera system, and exceptional performance. It balances power and efficiency for everyday use, while offering fast connectivity and smooth multitasking. The refined design feels comfortable in the hand and looks premium on the desk. With battery life built to last a full day, it is ideal for work, media, and creative apps. The camera captures sharp details in both bright and low-light scenes. iOS integration ensures a polished app ecosystem and reliable security updates. This device is perfect for users who want a high-end mobile companion.',
    images: ['https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_SL1500_.jpg',
    rating: 4.8,
    reviews: 1234,
    stock: 48,
    isFeatured: true,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'Mobiles',
    price: 1199,
    oldPrice: 1399,
    discountPercentage: 14,
    description: 'This premium Android smartphone offers a bright edge-to-edge screen, powerful chipset, and a polished camera system for photos and video. It is built for productivity, gaming, and media streaming with smooth performance throughout. The durable frame and premium finish make it feel solid and attractive. Battery life lasts through the day, and fast charging keeps you moving quickly. The software experience is customizable with modern Android features. It is ideal for users who want a cutting-edge phone with flagship hardware. The model excels as a productivity and entertainment device.',
    images: ['https://m.media-amazon.com/images/I/71q7RR9fWOL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71q7RR9fWOL._AC_SL1500_.jpg',
    rating: 4.7,
    reviews: 980,
    stock: 35,
    isFeatured: true,
    prime: true,
    deliveryDays: 3,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Sony WH1000XM6 Wireless Headphones',
    brand: 'Sony',
    category: 'Electronics',
    price: 349,
    oldPrice: 399,
    discountPercentage: 12,
    description: 'These premium wireless headphones combine excellent noise cancellation with crisp audio quality and long battery life. The soft ear cushions are comfortable for extended listening sessions. Adaptive sound control automatically adjusts to your surroundings so music stays immersive. The headset offers reliable Bluetooth pairing and convenient on-ear touch controls. Voice assistant support helps you manage playback hands-free. The carrying case makes them easy to travel with. These headphones are perfect for commuters, frequent travelers, and anyone who wants top-tier sound isolation.',
    images: ['https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SL1500_.jpg',
    rating: 4.6,
    reviews: 830,
    stock: 75,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Dell XPS 15 Laptop',
    brand: 'Dell',
    category: 'Laptops',
    price: 1449,
    oldPrice: 1699,
    discountPercentage: 14,
    description: 'This high-performance laptop blends a gorgeous display, powerful processor, and premium build quality in a compact package. It is well-suited for designers, developers, and content creators who need power on the go. The keyboard and trackpad are responsive and comfortable for long workflows. Fast storage and excellent thermal management keep performance smooth during demanding tasks. The high-resolution screen delivers vibrant colors and sharp detail for media work. It also offers a clean, professional look that fits both office and home settings. This model is a great choice for productivity and creativity.',
    images: ['https://m.media-amazon.com/images/I/91z8fpVl3jL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/91z8fpVl3jL._AC_SL1500_.jpg',
    rating: 4.6,
    reviews: 412,
    stock: 29,
    isFeatured: true,
    prime: false,
    deliveryDays: 4,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'MacBook Air M4',
    brand: 'Apple',
    category: 'Laptops',
    price: 1299,
    oldPrice: 1499,
    discountPercentage: 13,
    description: 'This ultraportable laptop delivers Apple M4 performance with an incredibly thin and light design. It is perfect for students, professionals, and travelers who need long battery life and effortless performance. The fanless architecture means whisper-quiet operation during everyday tasks. The display is clear and bright, making it excellent for browsing, document editing, and content consumption. Its responsive keyboard and large trackpad make typing and navigation easy. macOS integration delivers a smooth and secure user experience. It is ideal for users who want premium mobility with solid power.',
    images: ['https://m.media-amazon.com/images/I/71sq8iIi5DL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71sq8iIi5DL._AC_SL1500_.jpg',
    rating: 4.9,
    reviews: 620,
    stock: 58,
    isFeatured: true,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'PlayStation 5 Console',
    brand: 'Sony',
    category: 'Gaming',
    price: 499,
    oldPrice: 549,
    discountPercentage: 9,
    description: 'This next-generation gaming console delivers ultra-fast loading, stunning graphics, and immersive gameplay. Its custom controller features advanced haptic feedback and adaptive triggers for texture-rich gaming experiences. The console supports 4K gameplay and high frame rates for modern titles. Its expandable storage option lets you keep more games ready to play. The user interface is designed for quick access to games and media apps. It also includes multimedia streaming features for entertainment beyond gaming. This console is built for dedicated gamers and families who want powerful home entertainment.',
    images: ['https://m.media-amazon.com/images/I/619BkvKW35L._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/619BkvKW35L._AC_SL1500_.jpg',
    rating: 4.8,
    reviews: 1040,
    stock: 18,
    isFeatured: true,
    prime: false,
    deliveryDays: 4,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Nike Air Max 2024',
    brand: 'Nike',
    category: 'Shoes',
    price: 149,
    oldPrice: 179,
    discountPercentage: 17,
    description: 'These athletic sneakers feature modern cushioning and a sleek, supportive design for everyday wear and light training. The Air Max unit delivers responsive underfoot comfort while maintaining a trendy look. Breathable materials help keep your feet cool during all-day activities. The outsole provides dependable traction for walking and casual workouts. They are stylish enough for streetwear, yet comfortable enough for daily movement. The shoes combine performance and fashion in one versatile pair. These sneakers are a strong choice for runners and lifestyle users alike.',
    images: ['https://m.media-amazon.com/images/I/71AQBJkVpaL._AC_UX695_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71AQBJkVpaL._AC_UX695_.jpg',
    rating: 4.5,
    reviews: 540,
    stock: 110,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Adidas Ultraboost 24',
    brand: 'Adidas',
    category: 'Shoes',
    price: 179,
    oldPrice: 209,
    discountPercentage: 14,
    description: 'These running shoes are engineered for responsive energy return and superior comfort across long distances. The Boost midsole provides plush cushioning with every step while maintaining a lightweight feel. The knit upper conforms to your foot for a secure and breathable fit. Durable outsole traction keeps you stable on city streets and gym surfaces. They are designed for both serious runners and everyday fitness enthusiasts. The shoes look premium with clean styling and subtle detailing. They offer a polished running experience for athletes and casual runners.',
    images: ['https://m.media-amazon.com/images/I/71XViPeMhHL._AC_UX695_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71XViPeMhHL._AC_UX695_.jpg',
    rating: 4.7,
    reviews: 470,
    stock: 84,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'KitchenAid Artisan Stand Mixer',
    brand: 'KitchenAid',
    category: 'Kitchen',
    price: 429,
    oldPrice: 499,
    discountPercentage: 14,
    description: 'This versatile stand mixer is a kitchen workhorse built for baking, cooking, and meal prep. Its powerful motor and durable construction handle dough, batters, and sauces with ease. Included attachments allow you to whisk, mix, and knead consistently. The large mixing bowl accommodates family-sized recipes. It also makes it easy to prepare everything from homemade breads to creamy desserts. The mixer’s iconic design looks beautiful on the counter and stands up to frequent use. This appliance is perfect for home chefs and baking enthusiasts.',
    images: ['https://m.media-amazon.com/images/I/71W0Xx+5XfL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71W0Xx+5XfL._AC_SL1500_.jpg',
    rating: 4.8,
    reviews: 710,
    stock: 60,
    isFeatured: true,
    prime: false,
    deliveryDays: 3,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Boat Rockerz 330',
    brand: 'Boat',
    category: 'Electronics',
    price: 49,
    oldPrice: 79,
    discountPercentage: 38,
    description: 'These wireless headphones offer punchy bass and a lightweight design, all at an affordable price. They are comfortable for hours of music and easy to carry with the foldable build. Bluetooth pairing is quick and stable with most devices. The battery keeps you going for long playlists and movie watching. The on-ear controls let you manage music and calls without reaching for your phone. These headphones are ideal for casual listeners and commuters. They provide reliable sound quality for everyday use.',
    images: ['https://m.media-amazon.com/images/I/61JatGMt-XL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/61JatGMt-XL._AC_SL1500_.jpg',
    rating: 4.3,
    reviews: 361,
    stock: 180,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Nothing Phone 3',
    brand: 'Nothing',
    category: 'Mobiles',
    price: 699,
    oldPrice: 799,
    discountPercentage: 13,
    description: 'This standout smartphone combines a bold transparent style with dependable performance. The clean Android skin is easy to navigate and offers useful customization. The camera captures bright, balanced photos in most conditions. Fast charging keeps the battery ready during busy days. The display is sharp and colorful for video viewing and browsing. It feels premium in hand, thanks to the modern build and finish. This phone is a great choice for users who want distinctive design plus solid mid-range performance.',
    images: ['https://m.media-amazon.com/images/I/717HTqj+v4L._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/717HTqj+v4L._AC_SL1500_.jpg',
    rating: 4.2,
    reviews: 210,
    stock: 92,
    isFeatured: false,
    prime: true,
    deliveryDays: 3,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'OnePlus 13',
    brand: 'OnePlus',
    category: 'Mobiles',
    price: 799,
    oldPrice: 899,
    discountPercentage: 11,
    description: 'This phone delivers flagship-grade speed and a smooth display for gaming, multitasking, and media. The software is polished and responsive, keeping everyday interaction fluid. The fast charging technology refills the battery quickly when you’re on the move. The camera system takes vibrant shots with good detail and color. The durable finish feels premium during use. It excels for users who want a powerful phone without a premium price tag. This device is ideal for both productivity and entertainment.',
    images: ['https://m.media-amazon.com/images/I/712uTAuPfDL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/712uTAuPfDL._AC_SL1500_.jpg',
    rating: 4.6,
    reviews: 395,
    stock: 66,
    isFeatured: true,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Kindle Paperwhite',
    brand: 'Amazon',
    category: 'Books',
    price: 139,
    oldPrice: 159,
    discountPercentage: 13,
    description: 'This e-reader provides a crisp, glare-free display that feels like reading on real paper. It is waterproof, making it safe to read by the pool or in the bath. The battery lasts for weeks, eliminating constant charging. Adjustable lighting makes day and night reading comfortable. Access to the Kindle store gives you millions of books at your fingertips. Its compact design makes it easy to carry while traveling. This device is ideal for dedicated readers who want a distraction-free reading experience.',
    images: ['https://m.media-amazon.com/images/I/61u48FEsdHL._AC_SL1000_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/61u48FEsdHL._AC_SL1000_.jpg',
    rating: 4.7,
    reviews: 2100,
    stock: 125,
    isFeatured: true,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Canon EOS R50 Mirrorless Camera',
    brand: 'Canon',
    category: 'Electronics',
    price: 899,
    oldPrice: 999,
    discountPercentage: 10,
    description: 'This compact mirrorless camera delivers strong image quality in a travel-friendly body. It is capable of capturing sharp photos and smooth 4K video. Fast autofocus helps you track moving subjects with confidence. The touchscreen and intuitive controls make it accessible for new photographers. Its lightweight construction is comfortable for long shooting sessions. The camera offers advanced features for creative shooting. It is an excellent choice for content creators and hobbyists alike.',
    images: ['https://m.media-amazon.com/images/I/81ZYHkQh7uL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/81ZYHkQh7uL._AC_SL1500_.jpg',
    rating: 4.5,
    reviews: 250,
    stock: 40,
    isFeatured: false,
    prime: false,
    deliveryDays: 4,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'HP Pavilion 15 Laptop',
    brand: 'HP',
    category: 'Laptops',
    price: 749,
    oldPrice: 849,
    discountPercentage: 12,
    description: 'This everyday laptop is designed for reliable performance, productivity, and entertainment. It features a bright display and fast storage for launching apps quickly. The keyboard feels comfortable for writing and long work sessions. It handles browsing, video streaming, and work tasks with ease. The balanced design makes it practical for home, school, and office use. Its connectivity options support accessories and peripherals easily. This laptop is a solid choice for anyone who needs a dependable daily driver.',
    images: ['https://m.media-amazon.com/images/I/71jXkI1l5sL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71jXkI1l5sL._AC_SL1500_.jpg',
    rating: 4.3,
    reviews: 310,
    stock: 55,
    isFeatured: false,
    prime: true,
    deliveryDays: 3,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Samsung 55-inch QLED Smart TV',
    brand: 'Samsung',
    category: 'Electronics',
    price: 899,
    oldPrice: 1099,
    discountPercentage: 18,
    description: 'This large smart TV offers vivid QLED picture quality and strong HDR performance. The screen is designed for bright rooms and delivers punchy, colorful visuals. Smart TV apps make streaming movies and shows easy to access. The sleek bezel and modern stand fit well in living spaces. Built-in speakers provide solid sound for everyday viewing. It supports popular connectivity options for gaming and media devices. This television is ideal for home theaters, family rooms, and entertainment setups.',
    images: ['https://m.media-amazon.com/images/I/91z0V2XPssL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/91z0V2XPssL._AC_SL1500_.jpg',
    rating: 4.6,
    reviews: 520,
    stock: 34,
    isFeatured: true,
    prime: false,
    deliveryDays: 4,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Sony PlayStation DualSense Controller',
    brand: 'Sony',
    category: 'Gaming',
    price: 69,
    oldPrice: 79,
    discountPercentage: 13,
    description: 'This controller brings immersive haptic feedback and adaptive trigger resistance to modern gaming. It is ergonomically shaped for comfortable play sessions. The precision buttons and thumbsticks respond quickly to every input. The built-in speaker and microphone support easy voice chat and gameplay immersion. It pairs easily with PlayStation consoles and select PC titles. Its durable build feels premium and reliable. This is an excellent accessory for gamers who want an elevated control experience.',
    images: ['https://m.media-amazon.com/images/I/61b8Jd5f4BL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/61b8Jd5f4BL._AC_SL1500_.jpg',
    rating: 4.7,
    reviews: 870,
    stock: 95,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Logitech MX Master 3S Mouse',
    brand: 'Logitech',
    category: 'Electronics',
    price: 99,
    oldPrice: 129,
    discountPercentage: 23,
    description: 'This productivity mouse is built for comfort, precision, and efficiency. It features ergonomic contours that support the hand during long workdays. The scroll wheel is fast, accurate, and quiet for smooth navigation. Programmable buttons let you speed up repetitive tasks in your favorite apps. It tracks reliably on nearly any surface, including glass. The long battery life keeps you working without interruption. This mouse is ideal for designers, developers, and office professionals.',
    images: ['https://m.media-amazon.com/images/I/61xVnOeTN9L._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/61xVnOeTN9L._AC_SL1500_.jpg',
    rating: 4.8,
    reviews: 1450,
    stock: 125,
    isFeatured: true,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Philips Air Fryer XXL',
    brand: 'Philips',
    category: 'Kitchen',
    price: 199,
    oldPrice: 249,
    discountPercentage: 20,
    description: 'This large-capacity air fryer cooks crispy, healthier meals with minimal oil. It features easy-to-use controls and a roomy basket for family-style portions. The removable tray is simple to clean after cooking. Its fast-cooking design saves time while still delivering golden results. The appliance is versatile enough for fries, roasted veggies, and baked snacks. It is built for everyday home use and reliable performance. This air fryer is perfect for anyone who wants convenient, healthier cooking.',
    images: ['https://m.media-amazon.com/images/I/71wOQtpWxTL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71wOQtpWxTL._AC_SL1500_.jpg',
    rating: 4.4,
    reviews: 660,
    stock: 90,
    isFeatured: false,
    prime: true,
    deliveryDays: 3,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Apple Watch Series 10',
    brand: 'Apple',
    category: 'Electronics',
    price: 399,
    oldPrice: 449,
    discountPercentage: 11,
    description: 'This smartwatch blends health tracking, notifications, and seamless Apple integration on your wrist. It offers heart rate monitoring, workout tracking, and smart notifications. The bright display is easy to read in sunlight. It also supports music controls, calls, and quick access to apps. The watch is comfortable for all-day wear and durable for active use. It pairs perfectly with Apple devices for a cohesive experience. This smartwatch is ideal for fitness-minded users and tech enthusiasts.',
    images: ['https://m.media-amazon.com/images/I/71fXdG05YlL._AC_SL1500_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/71fXdG05YlL._AC_SL1500_.jpg',
    rating: 4.7,
    reviews: 780,
    stock: 68,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  },
  {
    title: 'Adidas Essentials Hoodie',
    brand: 'Adidas',
    category: 'Fashion',
    price: 69,
    oldPrice: 89,
    discountPercentage: 22,
    description: 'This hoodie offers soft comfort and a relaxed fit for everyday wear. It features a cozy hood and convenient kangaroo pocket for warmth and storage. Breathable fabric keeps you comfortable during cool weather. The classic style pairs easily with jeans, joggers, or athleisure looks. It is durable enough for frequent wear and retains its shape well. The hoodie is a staple layer for lounging or casual outings. It provides effortless comfort with sporty style.',
    images: ['https://m.media-amazon.com/images/I/61cW07lxywL._AC_UX679_.jpg'],
    thumbnail: 'https://m.media-amazon.com/images/I/61cW07lxywL._AC_UX679_.jpg',
    rating: 4.5,
    reviews: 410,
    stock: 140,
    isFeatured: false,
    prime: true,
    deliveryDays: 2,
    returnPolicy: '30-day return policy'
  }
]

const run = async () => {
  try {
    await mongoose.connect('mongodb://127.0.0.1:27017/amazon_clone', { useNewUrlParser: true, useUnifiedTopology: true })
    const titles = products.map((product) => product.title)
    const existing = await Product.find({ title: { $in: titles } }).select('title').lean()
    const existingTitles = new Set(existing.map((product) => product.title))
    const missing = products.filter((product) => !existingTitles.has(product.title))
    console.log('existing:', existing.length, 'missing:', missing.length)
    if (missing.length > 0) {
      await Product.insertMany(missing)
      console.log('inserted', missing.length)
    } else {
      console.log('no missing products inserted')
    }
    await mongoose.disconnect()
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

run()
