import re
from pathlib import Path

file_path = Path(__file__).parent / 'seedProducts.js'
text = file_path.read_text(encoding='utf-8')

replacements = {
    'Apple iPhone 16 Pro': "This flagship smartphone delivers a premium experience with a stunning OLED display, advanced camera system, and exceptional performance. It balances power and efficiency for everyday use, while offering fast connectivity and smooth multitasking. The refined design feels comfortable in the hand and looks premium on the desk. With battery life built to last a full day, it is ideal for work, media, and creative apps. The camera captures sharp details in both bright and low-light scenes. iOS integration ensures a polished app ecosystem and reliable security updates. This device is perfect for users who want a high-end mobile companion.",
    'Samsung Galaxy S25 Ultra': "This premium Android smartphone offers a bright edge-to-edge screen, powerful chipset, and a polished camera system for photos and video. It is built for productivity, gaming, and media streaming with smooth performance throughout. The durable frame and premium finish make it feel solid and attractive. Battery life lasts through the day, and fast charging keeps you moving quickly. The software experience is customizable with modern Android features. It is ideal for users who want a cutting-edge phone with flagship hardware. The model excels as a productivity and entertainment device.",
    'Sony WH1000XM6 Wireless Headphones': "These premium wireless headphones combine excellent noise cancellation with crisp audio quality and long battery life. The soft ear cushions are comfortable for extended listening sessions. Adaptive sound control automatically adjusts to your surroundings so music stays immersive. The headset offers reliable Bluetooth pairing and convenient on-ear touch controls. Voice assistant support helps you manage playback hands-free. The carrying case makes them easy to travel with. These headphones are perfect for commuters, frequent travelers, and anyone who wants top-tier sound isolation.",
    'Dell XPS 15 Laptop': "This high-performance laptop blends a gorgeous display, powerful processor, and premium build quality in a compact package. It is well-suited for designers, developers, and content creators who need power on the go. The keyboard and trackpad are responsive and comfortable for long workflows. Fast storage and excellent thermal management keep performance smooth during demanding tasks. The high-resolution screen delivers vibrant colors and sharp detail for media work. It also offers a clean, professional look that fits both office and home settings. This model is a great choice for productivity and creativity.",
    'MacBook Air M4': "This ultraportable laptop delivers Apple M4 performance with an incredibly thin and light design. It is perfect for students, professionals, and travelers who need long battery life and effortless performance. The fanless architecture means whisper-quiet operation during everyday tasks. The display is clear and bright, making it excellent for browsing, document editing, and content consumption. Its responsive keyboard and large trackpad make typing and navigation easy. macOS integration delivers a smooth and secure user experience. It is ideal for buyers who want premium mobility with solid power.",
    'PlayStation 5 Console': "This next-generation gaming console delivers ultra-fast loading, stunning graphics, and immersive gameplay. Its custom controller features advanced haptic feedback and adaptive triggers for texture-rich gaming experiences. The console supports 4K gaming and high frame rates for modern titles. Its expandable storage option lets you keep more games ready to play. The user interface is designed for quick access to games and media apps. It also includes multimedia streaming features for entertainment beyond gaming. This console is built for dedicated gamers and families who want powerful home entertainment.",
    'Nike Air Max 2024': "These athletic sneakers feature modern cushioning and a sleek, supportive design for everyday wear and light training. The Air Max unit delivers responsive underfoot comfort while maintaining a trendy look. Breathable materials help keep your feet cool during all-day activities. The outsole provides dependable traction for walking and casual workouts. They are stylish enough for streetwear, yet comfortable enough for daily movement. The shoes combine performance and fashion in one versatile pair. These sneakers are a strong choice for runners and lifestyle users alike.",
    'Adidas Ultraboost 24': "These running shoes are engineered for responsive energy return and superior comfort across long distances. The Boost midsole provides plush cushioning with every step while maintaining a lightweight feel. The knit upper conforms to your foot for a secure and breathable fit. Durable outsole traction keeps you stable on city streets and gym surfaces. They are designed for serious runners as well as everyday fitness enthusiasts. The shoes look premium with clean styling and subtle detailing. They offer a polished running experience for athletes and casual runners.",
    'KitchenAid Artisan Stand Mixer': "This versatile stand mixer is a kitchen workhorse built for baking, cooking, and meal prep. Its powerful motor and durable construction handle dough, batters, and sauces with ease. Included attachments allow you to whisk, mix, and knead consistently. The large mixing bowl accommodates family-sized recipes. It also makes it easy to prepare everything from homemade breads to creamy desserts. The iconic design looks beautiful on the counter and stands up to frequent use. This appliance is perfect for home chefs and baking enthusiasts.",
    'Boat Rockerz 330': "These wireless headphones offer punchy bass and a lightweight design, all at an affordable price. They are comfortable for hours of listening and easy to carry with the foldable build. Bluetooth pairing is quick and stable with most devices. The battery keeps you going for long playlists and movie watching. The on-ear controls let you manage music and calls without reaching for your phone. The headphones are ideal for casual music lovers and commuters. They provide reliable sound quality for everyday use.",
    'Nothing Phone 3': "This standout smartphone combines a bold transparent style with dependable performance. The clean Android skin is easy to navigate and offers useful customization. The camera captures bright, balanced photos in most conditions. Fast charging keeps the battery ready during busy days. The display is sharp and colorful for video viewing and browsing. It feels premium in hand, thanks to the modern build and finish. This phone is a great choice for users who want distinctive design plus solid mid-range performance.",
    'OnePlus 13': "This phone delivers flagship-grade speed and a smooth display for gaming, multitasking, and media. The software is polished and responsive, keeping everyday interaction fluid. The fast charging technology tops up the battery quickly when you’re on the move. The camera system takes vibrant shots with good detail and color. The design is refined, with premium materials and comfortable ergonomics. It excels for users who want a powerful phone without a premium price tag. The device is ideal for both productivity and entertainment.",
    'Kindle Paperwhite': "This e-reader provides a crisp, glare-free screen that feels like reading on real paper. It is waterproof, so you can read worry-free by the pool or at the beach. The battery lasts for weeks, eliminating constant charging concerns. Adjustable front lighting makes day and night reading comfortable. The Kindle library gives you access to millions of books and audiobooks. Its slim design makes it easy to carry on commutes and trips. This device is perfect for dedicated readers who want a focused reading experience.",
    'Canon EOS R50 Mirrorless Camera': "This compact mirrorless camera delivers strong image quality in a travel-friendly body. It is capable of capturing both sharp photos and smooth 4K video. Fast autofocus helps you track moving subjects with confidence. The touchscreen and intuitive controls make it accessible for new photographers. Lightweight construction makes it easy to carry on trips and everyday shoots. The camera also offers advanced features for creative shooting. It is an excellent choice for content creators and hobbyists alike.",
    'HP Pavilion 15 Laptop': "This everyday laptop is designed for reliable performance, productivity, and entertainment. It has a bright display and fast storage for launching apps quickly. The keyboard feels comfortable for writing and long work sessions. It handles browsing, video streaming, and work tasks without issue. The balanced design is practical for home, school, and office use. Its connectivity options support accessories and peripherals easily. This laptop is a solid choice for anyone who needs a dependable daily driver.",
    'Samsung 55-inch QLED Smart TV': "This large smart TV offers vivid QLED picture quality and strong HDR performance. The screen is designed for bright rooms and delivers punchy, colorful visuals. Smart TV apps make streaming movies and shows easy to access. The sleek bezel and modern stand fit well in living spaces. Built-in apps and connectivity support make it ideal for entertainment systems. The TV is great for movie nights, sports, and gaming. It provides a cinematic viewing experience for families and media lovers.",
    'Sony PlayStation DualSense Controller': "This controller brings immersive haptics and adaptive trigger resistance to modern gaming. It is ergonomically shaped for comfortable play sessions. The precision buttons and thumbsticks respond quickly to every input. Built-in speaker and microphone support enhance multiplayer communication and game immersion. It pairs easily with PlayStation consoles and select PC games. The controller is durable and well-suited for competitive gaming. It is a great companion for PlayStation users seeking an elevated experience.",
    'Logitech MX Master 3S Mouse': "This productivity mouse is built for comfort, precision, and efficiency. It features ergonomic contours that support the hand during long workdays. The scroll wheel is fast, accurate, and quiet for smooth navigation. Programmable buttons let you speed up repetitive tasks in your favorite apps. It tracks reliably on nearly any surface, including glass. The long battery life keeps you working without interruption. This mouse is ideal for designers, developers, and office professionals.",
    'Philips Air Fryer XXL': "This large-capacity air fryer cooks crispy, healthier meals using little to no oil. It has intuitive controls that simplify meal prep for families. The roomy basket fits multiple servings and is easy to clean. The appliance delivers even browning and consistent cooking results. It is versatile enough for fries, roasted veggies, and baked snacks. The compact design fits neatly on most kitchen counters. This air fryer is a strong choice for home cooks seeking quick, tasty, and healthier meals.",
    'Apple Watch Series 10': "This smartwatch blends health tracking, notifications, and seamless Apple integration on your wrist. It monitors workouts, heart rate, and daily activity with accurate sensors. The bright screen is easy to read during outdoor use. It also supports quick access to messages, music, and calls. The watch is comfortable for everyday wear and durable for active use. It pairs perfectly with Apple devices for a cohesive experience. This smartwatch is ideal for fitness-minded users and tech enthusiasts.",
    'Adidas Essentials Hoodie': "This hoodie offers soft comfort and a relaxed fit for everyday wear. It features a cozy hood and convenient kangaroo pocket for warmth and storage. Breathable fabric keeps you comfortable during workouts or casual outings. The classic style pairs easily with jeans, joggers, or athleisure wear. It is durable enough for frequent use and retains its shape well. The hoodie is suitable for lounging, running errands, or cool-weather layering. It provides reliable comfort with a clean, sporty look.",
}

for title, desc in replacements.items():
    pattern = re.compile(r"(title: '" + re.escape(title) + r"',[\s\S]*?description: ')[^']*('")
    match = pattern.search(text)
    if not match:
        raise ValueError(f"Title not found: {title}")
    text = pattern.sub(r"\1" + desc.replace('\\', '\\\\').replace("'", "\\'") + r"\2", text)

file_path.write_text(text, encoding='utf-8')
print('Descriptions updated')
